### ISSUE TITLE
fork in for loop

### ISSUE THREAD

**Issue by yavuzkoca** [oguzp1/operating-systems#1]
for (i = 0; i < k; i++) {
        f = fork();

        if (f == 0) {
            rl_ind = i;
            printf("Child %d created.\n", rl_ind);
            break;
        }
    }

in here, fork function should be called only if it is parent process, isn't it? So, I think it should be like:

    for (i = 0; i < k; i++) {
        if ( f > 0 )
            f = fork();

        if (f == 0) {
            rl_ind = i;
            printf("Child %d created.\n", rl_ind);
            break;
        }
    }

**Comment by oguzp1** [comment]
Child processes go inside the `if (f == 0)` check after being created and break out of the loop immediately. Effectively, only the parent process is able to call the `fork()` function.
